language: generic
env:
  global:
  - RAKUDO_URL="https://rakudo.perl6.org/downloads/rakudo/rakudo-2018.04.tar.gz"
  - PATH=/opt/rakudo-pkg/bin:$PATH
  - RAKUDO_DEB="https://github.com/nxadm/rakudo-pkg/releases/download/v2018.02.1/rakudo-pkg-Ubuntu14.04_2018.02.1-01_amd64.deb"
  matrix:
  - OS=alpine   ARCH=amd64 VERSION=3.6
  - OS=alpine   ARCH=amd64 VERSION=3.7
  - OS=centos   ARCH=amd64 VERSION=7
  - OS=debian   ARCH=amd64 VERSION=8
  - OS=debian   ARCH=amd64 VERSION=9
  - OS=fedora   ARCH=amd64 VERSION=26
  - OS=fedora   ARCH=amd64 VERSION=27
  - OS=opensuse ARCH=amd64 VERSION=42.3
  - OS=ubuntu   ARCH=amd64 VERSION=14.04
  - OS=ubuntu   ARCH=amd64 VERSION=16.04
  - OS=ubuntu   ARCH=amd64 VERSION=17.10
  - OS=ubuntu   ARCH=amd64 VERSION=14.04
  - OS=ubuntu   ARCH=i386 VERSION=16.04
  - OS=ubuntu   ARCH=i386 VERSION=17.10
sudo: required
services:
  - docker
install: 
  - set -e
  - wget $RAKUDO_DEB && sudo dpkg -i *.deb
script:
  - bin/create-img.p6 docker/Dockerfile-${OS}-${ARCH}-${VERSION}
  - docker run -ti --rm -e RAKUDO_URL=$RAKUDO_URL rakudo-pkg/$OS-$ARCH:$VERSION
